### ISSUE TITLE
Support for `const` keyword?

### ISSUE THREAD

**Issue by tylerbrandt** [sbrunner/jsonschema2md#201]
Can we add support for the [`const` keyword](https://json-schema.org/understanding-json-schema/reference/const) from draft 6? It's useful especially for "enum" types which have different sets of properties depending on the value of the enum, which we have modeled as an `anyOf` over multiple different definitions, each with a `source` property set to a `const` value. It's model-able as an `enum` with only one value, but it's not as clean that way (makes the schema definition more verbose and it's not as obvious in the docs what is intended).

**Comment by sbrunner** [comment]
Fixed by #250
